package song.pan.toolkit.mybatis.mapper;

import com.github.pagehelper.Page;
import org.apache.ibatis.annotations.Param;
import song.pan.toolkit.mybatis.entity.City;

import java.util.List;
import java.util.Map;

public interface CityMapper {


    // 参数注册，在 mapper.xml 中使用 #{param} 的形式
    List<City> betweenIds(@Param("from") int from, @Param("to") int to);

    // 用 Map 作为参数, 条件查询
    List<City> query(Map<String, Object> map);

    // 按位置传参
    List<City> populationLargerThan(int population, int limit);

    // 使用 list 作为参数
    List<City> citiesIn(List<Integer> list);

    // 自定义返回字段，存放在一个Map对象中
    List<Map<String, Object>> topRowsOf(int limit);

    // 分页查询
    Page<City> pagedQuery();


    int create(City record);

    int update(City record);

    int updateCity(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int updateByPrimaryKey(City record);
}