package song.pan.toolkit.mybatis.mapper;

import song.pan.toolkit.mybatis.entity.Country;

import java.util.List;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    Country selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    List<Country> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int updateByPrimaryKey(Country record);
}