package song.pan.toolkit.mybatis.mapper;

import org.apache.ibatis.annotations.Param;
import song.pan.toolkit.mybatis.entity.Countrylanguage;

import java.util.List;

public interface CountrylanguageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int deleteByPrimaryKey(@Param("countrycode") String countrycode, @Param("language") String language);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int insert(Countrylanguage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    Countrylanguage selectByPrimaryKey(@Param("countrycode") String countrycode, @Param("language") String language);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    List<Countrylanguage> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table countrylanguage
     *
     * @mbg.generated Thu Mar 25 11:53:40 CST 2021
     */
    int updateByPrimaryKey(Countrylanguage record);
}